/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"time"
)

// checks if the ConditionAvailable type satisfies the MappedNullable interface at compile time

// ConditionAvailable StatusAvailable is the status condition from an adapter that is used by CLM to compute the phase.
type ConditionAvailable struct {
	Type string
	// Condition status
	Status string
	// Machine-readable reason code
	Reason *string
	// Human-readable message
	Message            *string
	ObservedGeneration int32
	// Time when the condition was created  - In an adapter reporting conditions
	CreatedAt time.Time
	// Time when the condition was updated
	UpdatedAt time.Time
}

type _ConditionAvailable ConditionAvailable

// NewConditionAvailable instantiates a new ConditionAvailable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConditionAvailable(type_ string, status string, observedGeneration int32, createdAt time.Time, updatedAt time.Time) *ConditionAvailable {
	this := ConditionAvailable{}
	this.Type = type_
	this.Status = status
	this.ObservedGeneration = observedGeneration
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewConditionAvailableWithDefaults instantiates a new ConditionAvailable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConditionAvailableWithDefaults() *ConditionAvailable {
	this := ConditionAvailable{}
	return &this
}
