/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the NodePool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodePool{}

// NodePool struct for NodePool
type NodePool struct {
	// Resource identifier
	Id *string `json:"id,omitempty"`
	// Resource kind
	Kind *string `json:"kind,omitempty"`
	// Resource URI
	Href *string `json:"href,omitempty"`
	// labels for the API resource as pairs of name:value strings
	Labels    map[string]string `json:"labels"`
	CreatedAt time.Time         `json:"created_at"`
	UpdatedAt time.Time         `json:"updated_at"`
	// NodePool name (unique in a cluster)
	Name string `json:"name"`
	// Cluster specification CLM doesn't know how to unmarshall the spec, it only stores and forwards to adapters to do their job But CLM will validate the schema before accepting the request
	Spec            map[string]interface{} `json:"spec"`
	OwnerReferences ObjectReference        `json:"owner_references"`
	Status          NodePoolStatus         `json:"status"`
}

type _NodePool NodePool

// NewNodePool instantiates a new NodePool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodePool(labels map[string]string, createdAt time.Time, updatedAt time.Time, name string, spec map[string]interface{}, ownerReferences ObjectReference, status NodePoolStatus) *NodePool {
	this := NodePool{}
	this.Labels = labels
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Name = name
	this.Spec = spec
	this.OwnerReferences = ownerReferences
	this.Status = status
	return &this
}

// NewNodePoolWithDefaults instantiates a new NodePool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodePoolWithDefaults() *NodePool {
	this := NodePool{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NodePool) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodePool) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NodePool) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NodePool) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *NodePool) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodePool) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *NodePool) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *NodePool) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *NodePool) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodePool) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *NodePool) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *NodePool) SetHref(v string) {
	o.Href = &v
}

// GetLabels returns the Labels field value
func (o *NodePool) GetLabels() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *NodePool) GetLabelsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Labels, true
}

// SetLabels sets field value
func (o *NodePool) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *NodePool) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *NodePool) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *NodePool) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *NodePool) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *NodePool) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *NodePool) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetName returns the Name field value
func (o *NodePool) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NodePool) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NodePool) SetName(v string) {
	o.Name = v
}

// GetSpec returns the Spec field value
func (o *NodePool) GetSpec() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *NodePool) GetSpecOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Spec, true
}

// SetSpec sets field value
func (o *NodePool) SetSpec(v map[string]interface{}) {
	o.Spec = v
}

// GetOwnerReferences returns the OwnerReferences field value
func (o *NodePool) GetOwnerReferences() ObjectReference {
	if o == nil {
		var ret ObjectReference
		return ret
	}

	return o.OwnerReferences
}

// GetOwnerReferencesOk returns a tuple with the OwnerReferences field value
// and a boolean to check if the value has been set.
func (o *NodePool) GetOwnerReferencesOk() (*ObjectReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerReferences, true
}

// SetOwnerReferences sets field value
func (o *NodePool) SetOwnerReferences(v ObjectReference) {
	o.OwnerReferences = v
}

// GetStatus returns the Status field value
func (o *NodePool) GetStatus() NodePoolStatus {
	if o == nil {
		var ret NodePoolStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *NodePool) GetStatusOk() (*NodePoolStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *NodePool) SetStatus(v NodePoolStatus) {
	o.Status = v
}

func (o NodePool) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodePool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	toSerialize["labels"] = o.Labels
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["name"] = o.Name
	toSerialize["spec"] = o.Spec
	toSerialize["owner_references"] = o.OwnerReferences
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *NodePool) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"labels",
		"created_at",
		"updated_at",
		"name",
		"spec",
		"owner_references",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodePool := _NodePool{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNodePool)

	if err != nil {
		return err
	}

	*o = NodePool(varNodePool)

	return err
}

type NullableNodePool struct {
	value *NodePool
	isSet bool
}

func (v NullableNodePool) Get() *NodePool {
	return v.value
}

func (v *NullableNodePool) Set(val *NodePool) {
	v.value = val
	v.isSet = true
}

func (v NullableNodePool) IsSet() bool {
	return v.isSet
}

func (v *NullableNodePool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodePool(val *NodePool) *NullableNodePool {
	return &NullableNodePool{value: val, isSet: true}
}

func (v NullableNodePool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodePool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
