/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ConditionAvailable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConditionAvailable{}

// ConditionAvailable StatusAvailable is the status condition from an adapter that is used by CLM to compute the phase. `phase=ready` when all adaptors report `Available=true`
type ConditionAvailable struct {
	Type string `json:"type"`
	// Condition status
	Status string `json:"status"`
	// Machine-readable reason code
	Reason *string `json:"reason,omitempty"`
	// Human-readable message
	Message            *string `json:"message,omitempty"`
	ObservedGeneration int32   `json:"observed_generation"`
	// Time when the condition was created  - In an adapter reporting conditions `updated_at==created_at` - In the API, `created_at` doesn't change with new updates from adapters
	CreatedAt time.Time `json:"created_at"`
	// Time when the condition was updated
	UpdatedAt time.Time `json:"updated_at"`
}

type _ConditionAvailable ConditionAvailable

// NewConditionAvailable instantiates a new ConditionAvailable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConditionAvailable(type_ string, status string, observedGeneration int32, createdAt time.Time, updatedAt time.Time) *ConditionAvailable {
	this := ConditionAvailable{}
	this.Type = type_
	this.Status = status
	this.ObservedGeneration = observedGeneration
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewConditionAvailableWithDefaults instantiates a new ConditionAvailable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConditionAvailableWithDefaults() *ConditionAvailable {
	this := ConditionAvailable{}
	return &this
}

// GetType returns the Type field value
func (o *ConditionAvailable) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ConditionAvailable) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ConditionAvailable) SetType(v string) {
	o.Type = v
}

// GetStatus returns the Status field value
func (o *ConditionAvailable) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ConditionAvailable) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ConditionAvailable) SetStatus(v string) {
	o.Status = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *ConditionAvailable) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConditionAvailable) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *ConditionAvailable) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *ConditionAvailable) SetReason(v string) {
	o.Reason = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ConditionAvailable) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConditionAvailable) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ConditionAvailable) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ConditionAvailable) SetMessage(v string) {
	o.Message = &v
}

// GetObservedGeneration returns the ObservedGeneration field value
func (o *ConditionAvailable) GetObservedGeneration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ObservedGeneration
}

// GetObservedGenerationOk returns a tuple with the ObservedGeneration field value
// and a boolean to check if the value has been set.
func (o *ConditionAvailable) GetObservedGenerationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedGeneration, true
}

// SetObservedGeneration sets field value
func (o *ConditionAvailable) SetObservedGeneration(v int32) {
	o.ObservedGeneration = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ConditionAvailable) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ConditionAvailable) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ConditionAvailable) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ConditionAvailable) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ConditionAvailable) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ConditionAvailable) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ConditionAvailable) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConditionAvailable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["status"] = o.Status
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	toSerialize["observed_generation"] = o.ObservedGeneration
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ConditionAvailable) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"status",
		"observed_generation",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConditionAvailable := _ConditionAvailable{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConditionAvailable)

	if err != nil {
		return err
	}

	*o = ConditionAvailable(varConditionAvailable)

	return err
}

type NullableConditionAvailable struct {
	value *ConditionAvailable
	isSet bool
}

func (v NullableConditionAvailable) Get() *ConditionAvailable {
	return v.value
}

func (v *NullableConditionAvailable) Set(val *ConditionAvailable) {
	v.value = val
	v.isSet = true
}

func (v NullableConditionAvailable) IsSet() bool {
	return v.isSet
}

func (v *NullableConditionAvailable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConditionAvailable(val *ConditionAvailable) *NullableConditionAvailable {
	return &NullableConditionAvailable{value: val, isSet: true}
}

func (v NullableConditionAvailable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConditionAvailable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
