/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetNodePoolsStatuses200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNodePoolsStatuses200Response{}

// GetNodePoolsStatuses200Response struct for GetNodePoolsStatuses200Response
type GetNodePoolsStatuses200Response struct {
	Page  int32           `json:"page"`
	Size  int32           `json:"size"`
	Total int32           `json:"total"`
	Items []AdapterStatus `json:"items"`
}

type _GetNodePoolsStatuses200Response GetNodePoolsStatuses200Response

// NewGetNodePoolsStatuses200Response instantiates a new GetNodePoolsStatuses200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNodePoolsStatuses200Response(page int32, size int32, total int32, items []AdapterStatus) *GetNodePoolsStatuses200Response {
	this := GetNodePoolsStatuses200Response{}
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewGetNodePoolsStatuses200ResponseWithDefaults instantiates a new GetNodePoolsStatuses200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNodePoolsStatuses200ResponseWithDefaults() *GetNodePoolsStatuses200Response {
	this := GetNodePoolsStatuses200Response{}
	return &this
}

// GetPage returns the Page field value
func (o *GetNodePoolsStatuses200Response) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *GetNodePoolsStatuses200Response) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *GetNodePoolsStatuses200Response) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *GetNodePoolsStatuses200Response) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *GetNodePoolsStatuses200Response) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *GetNodePoolsStatuses200Response) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *GetNodePoolsStatuses200Response) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *GetNodePoolsStatuses200Response) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *GetNodePoolsStatuses200Response) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *GetNodePoolsStatuses200Response) GetItems() []AdapterStatus {
	if o == nil {
		var ret []AdapterStatus
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *GetNodePoolsStatuses200Response) GetItemsOk() ([]AdapterStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *GetNodePoolsStatuses200Response) SetItems(v []AdapterStatus) {
	o.Items = v
}

func (o GetNodePoolsStatuses200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNodePoolsStatuses200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *GetNodePoolsStatuses200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"page",
		"size",
		"total",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetNodePoolsStatuses200Response := _GetNodePoolsStatuses200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetNodePoolsStatuses200Response)

	if err != nil {
		return err
	}

	*o = GetNodePoolsStatuses200Response(varGetNodePoolsStatuses200Response)

	return err
}

type NullableGetNodePoolsStatuses200Response struct {
	value *GetNodePoolsStatuses200Response
	isSet bool
}

func (v NullableGetNodePoolsStatuses200Response) Get() *GetNodePoolsStatuses200Response {
	return v.value
}

func (v *NullableGetNodePoolsStatuses200Response) Set(val *GetNodePoolsStatuses200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNodePoolsStatuses200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNodePoolsStatuses200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNodePoolsStatuses200Response(val *GetNodePoolsStatuses200Response) *NullableGetNodePoolsStatuses200Response {
	return &NullableGetNodePoolsStatuses200Response{value: val, isSet: true}
}

func (v NullableGetNodePoolsStatuses200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNodePoolsStatuses200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
