/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AdapterStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdapterStatus{}

// AdapterStatus struct for AdapterStatus
type AdapterStatus struct {
	// Resource identifier
	Id *string `json:"id,omitempty"`
	// Resource kind
	Kind *string `json:"kind,omitempty"`
	// Resource URI
	Href *string `json:"href,omitempty"`
	// labels for the API resource as pairs of name:value strings
	Labels    map[string]string `json:"labels"`
	CreatedAt time.Time         `json:"created_at"`
	UpdatedAt time.Time         `json:"updated_at"`
	// Name of the adapter that generated this status (Validator, DNS...)
	AdapterName string `json:"adapter_name"`
	// Reference to the cluster to which this adapter status pertains
	OwnerReferences ObjectReference `json:"owner_references"`
	// Which generation for an entity (Clusters, NodePools) was current at the time of creating this status
	ObservedGeneration int32 `json:"observed_generation"`
	// Kubernetes-style conditions tracking adapter state
	Conditions []Condition `json:"conditions"`
	// Adapter-specific data (structure varies by adapter type)
	Data     map[string]interface{} `json:"data,omitempty"`
	Metadata *AdapterStatusMetadata `json:"metadata,omitempty"`
}

type _AdapterStatus AdapterStatus

// NewAdapterStatus instantiates a new AdapterStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdapterStatus(labels map[string]string, createdAt time.Time, updatedAt time.Time, adapterName string, ownerReferences ObjectReference, observedGeneration int32, conditions []Condition) *AdapterStatus {
	this := AdapterStatus{}
	this.Labels = labels
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.AdapterName = adapterName
	this.OwnerReferences = ownerReferences
	this.ObservedGeneration = observedGeneration
	this.Conditions = conditions
	return &this
}

// NewAdapterStatusWithDefaults instantiates a new AdapterStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdapterStatusWithDefaults() *AdapterStatus {
	this := AdapterStatus{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AdapterStatus) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AdapterStatus) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AdapterStatus) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *AdapterStatus) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *AdapterStatus) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *AdapterStatus) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *AdapterStatus) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *AdapterStatus) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *AdapterStatus) SetHref(v string) {
	o.Href = &v
}

// GetLabels returns the Labels field value
func (o *AdapterStatus) GetLabels() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetLabelsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Labels, true
}

// SetLabels sets field value
func (o *AdapterStatus) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AdapterStatus) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AdapterStatus) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AdapterStatus) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AdapterStatus) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetAdapterName returns the AdapterName field value
func (o *AdapterStatus) GetAdapterName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdapterName
}

// GetAdapterNameOk returns a tuple with the AdapterName field value
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetAdapterNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdapterName, true
}

// SetAdapterName sets field value
func (o *AdapterStatus) SetAdapterName(v string) {
	o.AdapterName = v
}

// GetOwnerReferences returns the OwnerReferences field value
func (o *AdapterStatus) GetOwnerReferences() ObjectReference {
	if o == nil {
		var ret ObjectReference
		return ret
	}

	return o.OwnerReferences
}

// GetOwnerReferencesOk returns a tuple with the OwnerReferences field value
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetOwnerReferencesOk() (*ObjectReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerReferences, true
}

// SetOwnerReferences sets field value
func (o *AdapterStatus) SetOwnerReferences(v ObjectReference) {
	o.OwnerReferences = v
}

// GetObservedGeneration returns the ObservedGeneration field value
func (o *AdapterStatus) GetObservedGeneration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ObservedGeneration
}

// GetObservedGenerationOk returns a tuple with the ObservedGeneration field value
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetObservedGenerationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedGeneration, true
}

// SetObservedGeneration sets field value
func (o *AdapterStatus) SetObservedGeneration(v int32) {
	o.ObservedGeneration = v
}

// GetConditions returns the Conditions field value
func (o *AdapterStatus) GetConditions() []Condition {
	if o == nil {
		var ret []Condition
		return ret
	}

	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetConditionsOk() ([]Condition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Conditions, true
}

// SetConditions sets field value
func (o *AdapterStatus) SetConditions(v []Condition) {
	o.Conditions = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AdapterStatus) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AdapterStatus) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *AdapterStatus) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *AdapterStatus) GetMetadata() AdapterStatusMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret AdapterStatusMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetMetadataOk() (*AdapterStatusMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *AdapterStatus) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given AdapterStatusMetadata and assigns it to the Metadata field.
func (o *AdapterStatus) SetMetadata(v AdapterStatusMetadata) {
	o.Metadata = &v
}

func (o AdapterStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdapterStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	toSerialize["labels"] = o.Labels
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["adapter_name"] = o.AdapterName
	toSerialize["owner_references"] = o.OwnerReferences
	toSerialize["observed_generation"] = o.ObservedGeneration
	toSerialize["conditions"] = o.Conditions
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *AdapterStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"labels",
		"created_at",
		"updated_at",
		"adapter_name",
		"owner_references",
		"observed_generation",
		"conditions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdapterStatus := _AdapterStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdapterStatus)

	if err != nil {
		return err
	}

	*o = AdapterStatus(varAdapterStatus)

	return err
}

type NullableAdapterStatus struct {
	value *AdapterStatus
	isSet bool
}

func (v NullableAdapterStatus) Get() *AdapterStatus {
	return v.value
}

func (v *NullableAdapterStatus) Set(val *AdapterStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableAdapterStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableAdapterStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdapterStatus(val *AdapterStatus) *NullableAdapterStatus {
	return &NullableAdapterStatus{value: val, isSet: true}
}

func (v NullableAdapterStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdapterStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
