/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the NodePoolStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodePoolStatus{}

// NodePoolStatus struct for NodePoolStatus
type NodePoolStatus struct {
	// Current NodePool phase (native database column). Updated when adapters report status. Note: status.phase provides aggregated view from all adapter conditions.
	Phase string `json:"phase"`
	// Last generation processed by adapters Updated when adapters report status. This will be the lowest value of each adapter's observed_generation values The phase value is based on this generation
	ObservedGeneration int32 `json:"observed_generation"`
	// When NodePool last transitioned (updated by adapters, used by Sentinel for backoff)
	LastTransitionTime time.Time `json:"last_transition_time"`
	// Time of the last complete report from adapters Updated when adapters report status. Oldest `updated_at` from the adapter conditions
	UpdatedAt time.Time            `json:"updated_at"`
	Adapters  []ConditionAvailable `json:"adapters"`
}

type _NodePoolStatus NodePoolStatus

// NewNodePoolStatus instantiates a new NodePoolStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodePoolStatus(phase string, observedGeneration int32, lastTransitionTime time.Time, updatedAt time.Time, adapters []ConditionAvailable) *NodePoolStatus {
	this := NodePoolStatus{}
	this.Phase = phase
	this.ObservedGeneration = observedGeneration
	this.LastTransitionTime = lastTransitionTime
	this.UpdatedAt = updatedAt
	this.Adapters = adapters
	return &this
}

// NewNodePoolStatusWithDefaults instantiates a new NodePoolStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodePoolStatusWithDefaults() *NodePoolStatus {
	this := NodePoolStatus{}
	return &this
}

// GetPhase returns the Phase field value
func (o *NodePoolStatus) GetPhase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value
// and a boolean to check if the value has been set.
func (o *NodePoolStatus) GetPhaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase, true
}

// SetPhase sets field value
func (o *NodePoolStatus) SetPhase(v string) {
	o.Phase = v
}

// GetObservedGeneration returns the ObservedGeneration field value
func (o *NodePoolStatus) GetObservedGeneration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ObservedGeneration
}

// GetObservedGenerationOk returns a tuple with the ObservedGeneration field value
// and a boolean to check if the value has been set.
func (o *NodePoolStatus) GetObservedGenerationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedGeneration, true
}

// SetObservedGeneration sets field value
func (o *NodePoolStatus) SetObservedGeneration(v int32) {
	o.ObservedGeneration = v
}

// GetLastTransitionTime returns the LastTransitionTime field value
func (o *NodePoolStatus) GetLastTransitionTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastTransitionTime
}

// GetLastTransitionTimeOk returns a tuple with the LastTransitionTime field value
// and a boolean to check if the value has been set.
func (o *NodePoolStatus) GetLastTransitionTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastTransitionTime, true
}

// SetLastTransitionTime sets field value
func (o *NodePoolStatus) SetLastTransitionTime(v time.Time) {
	o.LastTransitionTime = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *NodePoolStatus) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *NodePoolStatus) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *NodePoolStatus) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetAdapters returns the Adapters field value
func (o *NodePoolStatus) GetAdapters() []ConditionAvailable {
	if o == nil {
		var ret []ConditionAvailable
		return ret
	}

	return o.Adapters
}

// GetAdaptersOk returns a tuple with the Adapters field value
// and a boolean to check if the value has been set.
func (o *NodePoolStatus) GetAdaptersOk() ([]ConditionAvailable, bool) {
	if o == nil {
		return nil, false
	}
	return o.Adapters, true
}

// SetAdapters sets field value
func (o *NodePoolStatus) SetAdapters(v []ConditionAvailable) {
	o.Adapters = v
}

func (o NodePoolStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodePoolStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phase"] = o.Phase
	toSerialize["observed_generation"] = o.ObservedGeneration
	toSerialize["last_transition_time"] = o.LastTransitionTime
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["adapters"] = o.Adapters
	return toSerialize, nil
}

func (o *NodePoolStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phase",
		"observed_generation",
		"last_transition_time",
		"updated_at",
		"adapters",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodePoolStatus := _NodePoolStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNodePoolStatus)

	if err != nil {
		return err
	}

	*o = NodePoolStatus(varNodePoolStatus)

	return err
}

type NullableNodePoolStatus struct {
	value *NodePoolStatus
	isSet bool
}

func (v NullableNodePoolStatus) Get() *NodePoolStatus {
	return v.value
}

func (v *NullableNodePoolStatus) Set(val *NodePoolStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableNodePoolStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableNodePoolStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodePoolStatus(val *NodePoolStatus) *NullableNodePoolStatus {
	return &NullableNodePoolStatus{value: val, isSet: true}
}

func (v NullableNodePoolStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodePoolStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
