/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// GetClusterById200Response struct for GetClusterById200Response
type GetClusterById200Response struct {
	Cluster *Cluster
	Error   *Error
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetClusterById200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Cluster
	err = json.Unmarshal(data, &dst.Cluster)
	if err == nil {
		jsonCluster, _ := json.Marshal(dst.Cluster)
		if string(jsonCluster) == "{}" { // empty struct
			dst.Cluster = nil
		} else {
			return nil // data stored in dst.Cluster, return on the first match
		}
	} else {
		dst.Cluster = nil
	}

	// try to unmarshal JSON data into Error
	err = json.Unmarshal(data, &dst.Error)
	if err == nil {
		jsonError, _ := json.Marshal(dst.Error)
		if string(jsonError) == "{}" { // empty struct
			dst.Error = nil
		} else {
			return nil // data stored in dst.Error, return on the first match
		}
	} else {
		dst.Error = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetClusterById200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetClusterById200Response) MarshalJSON() ([]byte, error) {
	if src.Cluster != nil {
		return json.Marshal(&src.Cluster)
	}

	if src.Error != nil {
		return json.Marshal(&src.Error)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableGetClusterById200Response struct {
	value *GetClusterById200Response
	isSet bool
}

func (v NullableGetClusterById200Response) Get() *GetClusterById200Response {
	return v.value
}

func (v *NullableGetClusterById200Response) Set(val *GetClusterById200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClusterById200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClusterById200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClusterById200Response(val *GetClusterById200Response) *NullableGetClusterById200Response {
	return &NullableGetClusterById200Response{value: val, isSet: true}
}

func (v NullableGetClusterById200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClusterById200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
