/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AdapterStatusCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdapterStatusCreateRequest{}

// AdapterStatusCreateRequest struct for AdapterStatusCreateRequest
type AdapterStatusCreateRequest struct {
	// Adapter identifier
	AdapterName string `json:"adapter_name"`
	// Which cluster generation this status reflects
	ObservedGeneration int32       `json:"observed_generation"`
	Conditions         []Condition `json:"conditions"`
	// Adapter-specific data
	Data map[string]interface{} `json:"data,omitempty"`
	// Job execution metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _AdapterStatusCreateRequest AdapterStatusCreateRequest

// NewAdapterStatusCreateRequest instantiates a new AdapterStatusCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdapterStatusCreateRequest(adapterName string, observedGeneration int32, conditions []Condition) *AdapterStatusCreateRequest {
	this := AdapterStatusCreateRequest{}
	this.AdapterName = adapterName
	this.ObservedGeneration = observedGeneration
	this.Conditions = conditions
	return &this
}

// NewAdapterStatusCreateRequestWithDefaults instantiates a new AdapterStatusCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdapterStatusCreateRequestWithDefaults() *AdapterStatusCreateRequest {
	this := AdapterStatusCreateRequest{}
	return &this
}

// GetAdapterName returns the AdapterName field value
func (o *AdapterStatusCreateRequest) GetAdapterName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdapterName
}

// GetAdapterNameOk returns a tuple with the AdapterName field value
// and a boolean to check if the value has been set.
func (o *AdapterStatusCreateRequest) GetAdapterNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdapterName, true
}

// SetAdapterName sets field value
func (o *AdapterStatusCreateRequest) SetAdapterName(v string) {
	o.AdapterName = v
}

// GetObservedGeneration returns the ObservedGeneration field value
func (o *AdapterStatusCreateRequest) GetObservedGeneration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ObservedGeneration
}

// GetObservedGenerationOk returns a tuple with the ObservedGeneration field value
// and a boolean to check if the value has been set.
func (o *AdapterStatusCreateRequest) GetObservedGenerationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedGeneration, true
}

// SetObservedGeneration sets field value
func (o *AdapterStatusCreateRequest) SetObservedGeneration(v int32) {
	o.ObservedGeneration = v
}

// GetConditions returns the Conditions field value
func (o *AdapterStatusCreateRequest) GetConditions() []Condition {
	if o == nil {
		var ret []Condition
		return ret
	}

	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value
// and a boolean to check if the value has been set.
func (o *AdapterStatusCreateRequest) GetConditionsOk() ([]Condition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Conditions, true
}

// SetConditions sets field value
func (o *AdapterStatusCreateRequest) SetConditions(v []Condition) {
	o.Conditions = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AdapterStatusCreateRequest) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatusCreateRequest) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AdapterStatusCreateRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *AdapterStatusCreateRequest) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *AdapterStatusCreateRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatusCreateRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *AdapterStatusCreateRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *AdapterStatusCreateRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o AdapterStatusCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdapterStatusCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["adapter_name"] = o.AdapterName
	toSerialize["observed_generation"] = o.ObservedGeneration
	toSerialize["conditions"] = o.Conditions
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *AdapterStatusCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"adapter_name",
		"observed_generation",
		"conditions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdapterStatusCreateRequest := _AdapterStatusCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdapterStatusCreateRequest)

	if err != nil {
		return err
	}

	*o = AdapterStatusCreateRequest(varAdapterStatusCreateRequest)

	return err
}

type NullableAdapterStatusCreateRequest struct {
	value *AdapterStatusCreateRequest
	isSet bool
}

func (v NullableAdapterStatusCreateRequest) Get() *AdapterStatusCreateRequest {
	return v.value
}

func (v *NullableAdapterStatusCreateRequest) Set(val *AdapterStatusCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAdapterStatusCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAdapterStatusCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdapterStatusCreateRequest(val *AdapterStatusCreateRequest) *NullableAdapterStatusCreateRequest {
	return &NullableAdapterStatusCreateRequest{value: val, isSet: true}
}

func (v NullableAdapterStatusCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdapterStatusCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
