/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetNodePoolsByClusterId200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNodePoolsByClusterId200Response{}

// GetNodePoolsByClusterId200Response struct for GetNodePoolsByClusterId200Response
type GetNodePoolsByClusterId200Response struct {
	Page  int32      `json:"page"`
	Size  int32      `json:"size"`
	Total int32      `json:"total"`
	Items []NodePool `json:"items"`
}

type _GetNodePoolsByClusterId200Response GetNodePoolsByClusterId200Response

// NewGetNodePoolsByClusterId200Response instantiates a new GetNodePoolsByClusterId200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNodePoolsByClusterId200Response(page int32, size int32, total int32, items []NodePool) *GetNodePoolsByClusterId200Response {
	this := GetNodePoolsByClusterId200Response{}
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewGetNodePoolsByClusterId200ResponseWithDefaults instantiates a new GetNodePoolsByClusterId200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNodePoolsByClusterId200ResponseWithDefaults() *GetNodePoolsByClusterId200Response {
	this := GetNodePoolsByClusterId200Response{}
	return &this
}

// GetPage returns the Page field value
func (o *GetNodePoolsByClusterId200Response) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *GetNodePoolsByClusterId200Response) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *GetNodePoolsByClusterId200Response) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *GetNodePoolsByClusterId200Response) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *GetNodePoolsByClusterId200Response) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *GetNodePoolsByClusterId200Response) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *GetNodePoolsByClusterId200Response) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *GetNodePoolsByClusterId200Response) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *GetNodePoolsByClusterId200Response) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *GetNodePoolsByClusterId200Response) GetItems() []NodePool {
	if o == nil {
		var ret []NodePool
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *GetNodePoolsByClusterId200Response) GetItemsOk() ([]NodePool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *GetNodePoolsByClusterId200Response) SetItems(v []NodePool) {
	o.Items = v
}

func (o GetNodePoolsByClusterId200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNodePoolsByClusterId200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *GetNodePoolsByClusterId200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"page",
		"size",
		"total",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetNodePoolsByClusterId200Response := _GetNodePoolsByClusterId200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetNodePoolsByClusterId200Response)

	if err != nil {
		return err
	}

	*o = GetNodePoolsByClusterId200Response(varGetNodePoolsByClusterId200Response)

	return err
}

type NullableGetNodePoolsByClusterId200Response struct {
	value *GetNodePoolsByClusterId200Response
	isSet bool
}

func (v NullableGetNodePoolsByClusterId200Response) Get() *GetNodePoolsByClusterId200Response {
	return v.value
}

func (v *NullableGetNodePoolsByClusterId200Response) Set(val *GetNodePoolsByClusterId200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNodePoolsByClusterId200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNodePoolsByClusterId200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNodePoolsByClusterId200Response(val *GetNodePoolsByClusterId200Response) *NullableGetNodePoolsByClusterId200Response {
	return &NullableGetNodePoolsByClusterId200Response{value: val, isSet: true}
}

func (v NullableGetNodePoolsByClusterId200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNodePoolsByClusterId200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
