/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the NodePoolCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodePoolCreateRequest{}

// NodePoolCreateRequest struct for NodePoolCreateRequest
type NodePoolCreateRequest struct {
	// Resource identifier
	Id *string `json:"id,omitempty"`
	// Resource kind
	Kind *string `json:"kind,omitempty"`
	// Resource URI
	Href *string `json:"href,omitempty"`
	// labels for the API resource as pairs of name:value strings
	Labels    map[string]string `json:"labels"`
	CreatedAt time.Time         `json:"created_at"`
	UpdatedAt time.Time         `json:"updated_at"`
	// NodePool name (unique in a cluster)
	Name string `json:"name"`
	// Cluster specification CLM doesn't know how to unmarshall the spec, it only stores and forwards to adapters to do their job But CLM will validate the schema before accepting the request
	Spec map[string]interface{} `json:"spec"`
}

type _NodePoolCreateRequest NodePoolCreateRequest

// NewNodePoolCreateRequest instantiates a new NodePoolCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodePoolCreateRequest(labels map[string]string, createdAt time.Time, updatedAt time.Time, name string, spec map[string]interface{}) *NodePoolCreateRequest {
	this := NodePoolCreateRequest{}
	this.Labels = labels
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Name = name
	this.Spec = spec
	return &this
}

// NewNodePoolCreateRequestWithDefaults instantiates a new NodePoolCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodePoolCreateRequestWithDefaults() *NodePoolCreateRequest {
	this := NodePoolCreateRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NodePoolCreateRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodePoolCreateRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NodePoolCreateRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NodePoolCreateRequest) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *NodePoolCreateRequest) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodePoolCreateRequest) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *NodePoolCreateRequest) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *NodePoolCreateRequest) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *NodePoolCreateRequest) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodePoolCreateRequest) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *NodePoolCreateRequest) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *NodePoolCreateRequest) SetHref(v string) {
	o.Href = &v
}

// GetLabels returns the Labels field value
func (o *NodePoolCreateRequest) GetLabels() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *NodePoolCreateRequest) GetLabelsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Labels, true
}

// SetLabels sets field value
func (o *NodePoolCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *NodePoolCreateRequest) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *NodePoolCreateRequest) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *NodePoolCreateRequest) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *NodePoolCreateRequest) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *NodePoolCreateRequest) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *NodePoolCreateRequest) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetName returns the Name field value
func (o *NodePoolCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NodePoolCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NodePoolCreateRequest) SetName(v string) {
	o.Name = v
}

// GetSpec returns the Spec field value
func (o *NodePoolCreateRequest) GetSpec() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *NodePoolCreateRequest) GetSpecOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Spec, true
}

// SetSpec sets field value
func (o *NodePoolCreateRequest) SetSpec(v map[string]interface{}) {
	o.Spec = v
}

func (o NodePoolCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodePoolCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	toSerialize["labels"] = o.Labels
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["name"] = o.Name
	toSerialize["spec"] = o.Spec
	return toSerialize, nil
}

func (o *NodePoolCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"labels",
		"created_at",
		"updated_at",
		"name",
		"spec",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodePoolCreateRequest := _NodePoolCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNodePoolCreateRequest)

	if err != nil {
		return err
	}

	*o = NodePoolCreateRequest(varNodePoolCreateRequest)

	return err
}

type NullableNodePoolCreateRequest struct {
	value *NodePoolCreateRequest
	isSet bool
}

func (v NullableNodePoolCreateRequest) Get() *NodePoolCreateRequest {
	return v.value
}

func (v *NullableNodePoolCreateRequest) Set(val *NodePoolCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNodePoolCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNodePoolCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodePoolCreateRequest(val *NodePoolCreateRequest) *NullableNodePoolCreateRequest {
	return &NullableNodePoolCreateRequest{value: val, isSet: true}
}

func (v NullableNodePoolCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodePoolCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
