/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ClusterCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterCreateRequest{}

// ClusterCreateRequest struct for ClusterCreateRequest
type ClusterCreateRequest struct {
	Kind string `json:"kind"`
	// Cluster name (unique)
	Name string `json:"name"`
	// Cluster specification CLM doesn't know how to unmarshall the spec, it only stores and forwards to adapters to do their job But CLM will validate the schema before accepting the request
	Spec map[string]interface{} `json:"spec"`
	// Resource identifier
	Id *string `json:"id,omitempty"`
	// Resource URI
	Href *string `json:"href,omitempty"`
	// labels for the API resource as pairs of name:value strings
	Labels    map[string]string `json:"labels"`
	CreatedAt time.Time         `json:"created_at"`
	UpdatedAt time.Time         `json:"updated_at"`
}

type _ClusterCreateRequest ClusterCreateRequest

// NewClusterCreateRequest instantiates a new ClusterCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterCreateRequest(kind string, name string, spec map[string]interface{}, labels map[string]string, createdAt time.Time, updatedAt time.Time) *ClusterCreateRequest {
	this := ClusterCreateRequest{}
	this.Kind = kind
	this.Name = name
	this.Spec = spec
	this.Labels = labels
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewClusterCreateRequestWithDefaults instantiates a new ClusterCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterCreateRequestWithDefaults() *ClusterCreateRequest {
	this := ClusterCreateRequest{}
	var kind string = "Cluster"
	this.Kind = kind
	return &this
}

// GetKind returns the Kind field value
func (o *ClusterCreateRequest) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ClusterCreateRequest) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ClusterCreateRequest) SetKind(v string) {
	o.Kind = v
}

// GetName returns the Name field value
func (o *ClusterCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ClusterCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ClusterCreateRequest) SetName(v string) {
	o.Name = v
}

// GetSpec returns the Spec field value
func (o *ClusterCreateRequest) GetSpec() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *ClusterCreateRequest) GetSpecOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Spec, true
}

// SetSpec sets field value
func (o *ClusterCreateRequest) SetSpec(v map[string]interface{}) {
	o.Spec = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ClusterCreateRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterCreateRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ClusterCreateRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ClusterCreateRequest) SetId(v string) {
	o.Id = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ClusterCreateRequest) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterCreateRequest) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ClusterCreateRequest) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ClusterCreateRequest) SetHref(v string) {
	o.Href = &v
}

// GetLabels returns the Labels field value
func (o *ClusterCreateRequest) GetLabels() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *ClusterCreateRequest) GetLabelsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Labels, true
}

// SetLabels sets field value
func (o *ClusterCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ClusterCreateRequest) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ClusterCreateRequest) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ClusterCreateRequest) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ClusterCreateRequest) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ClusterCreateRequest) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ClusterCreateRequest) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ClusterCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	toSerialize["spec"] = o.Spec
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	toSerialize["labels"] = o.Labels
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *ClusterCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"name",
		"spec",
		"labels",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterCreateRequest := _ClusterCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterCreateRequest)

	if err != nil {
		return err
	}

	*o = ClusterCreateRequest(varClusterCreateRequest)

	return err
}

type NullableClusterCreateRequest struct {
	value *ClusterCreateRequest
	isSet bool
}

func (v NullableClusterCreateRequest) Get() *ClusterCreateRequest {
	return v.value
}

func (v *NullableClusterCreateRequest) Set(val *ClusterCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterCreateRequest(val *ClusterCreateRequest) *NullableClusterCreateRequest {
	return &NullableClusterCreateRequest{value: val, isSet: true}
}

func (v NullableClusterCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
