/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the AdapterStatusMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdapterStatusMetadata{}

// AdapterStatusMetadata Metadata about the adapter job/execution
type AdapterStatusMetadata struct {
	JobName      *string    `json:"job_name,omitempty"`
	JobNamespace *string    `json:"job_namespace,omitempty"`
	Attempt      *int32     `json:"attempt,omitempty"`
	StartedAt    *time.Time `json:"started_at,omitempty"`
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	Duration     *string    `json:"duration,omitempty"`
}

// NewAdapterStatusMetadata instantiates a new AdapterStatusMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdapterStatusMetadata() *AdapterStatusMetadata {
	this := AdapterStatusMetadata{}
	return &this
}

// NewAdapterStatusMetadataWithDefaults instantiates a new AdapterStatusMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdapterStatusMetadataWithDefaults() *AdapterStatusMetadata {
	this := AdapterStatusMetadata{}
	return &this
}

// GetJobName returns the JobName field value if set, zero value otherwise.
func (o *AdapterStatusMetadata) GetJobName() string {
	if o == nil || IsNil(o.JobName) {
		var ret string
		return ret
	}
	return *o.JobName
}

// GetJobNameOk returns a tuple with the JobName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatusMetadata) GetJobNameOk() (*string, bool) {
	if o == nil || IsNil(o.JobName) {
		return nil, false
	}
	return o.JobName, true
}

// HasJobName returns a boolean if a field has been set.
func (o *AdapterStatusMetadata) HasJobName() bool {
	if o != nil && !IsNil(o.JobName) {
		return true
	}

	return false
}

// SetJobName gets a reference to the given string and assigns it to the JobName field.
func (o *AdapterStatusMetadata) SetJobName(v string) {
	o.JobName = &v
}

// GetJobNamespace returns the JobNamespace field value if set, zero value otherwise.
func (o *AdapterStatusMetadata) GetJobNamespace() string {
	if o == nil || IsNil(o.JobNamespace) {
		var ret string
		return ret
	}
	return *o.JobNamespace
}

// GetJobNamespaceOk returns a tuple with the JobNamespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatusMetadata) GetJobNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.JobNamespace) {
		return nil, false
	}
	return o.JobNamespace, true
}

// HasJobNamespace returns a boolean if a field has been set.
func (o *AdapterStatusMetadata) HasJobNamespace() bool {
	if o != nil && !IsNil(o.JobNamespace) {
		return true
	}

	return false
}

// SetJobNamespace gets a reference to the given string and assigns it to the JobNamespace field.
func (o *AdapterStatusMetadata) SetJobNamespace(v string) {
	o.JobNamespace = &v
}

// GetAttempt returns the Attempt field value if set, zero value otherwise.
func (o *AdapterStatusMetadata) GetAttempt() int32 {
	if o == nil || IsNil(o.Attempt) {
		var ret int32
		return ret
	}
	return *o.Attempt
}

// GetAttemptOk returns a tuple with the Attempt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatusMetadata) GetAttemptOk() (*int32, bool) {
	if o == nil || IsNil(o.Attempt) {
		return nil, false
	}
	return o.Attempt, true
}

// HasAttempt returns a boolean if a field has been set.
func (o *AdapterStatusMetadata) HasAttempt() bool {
	if o != nil && !IsNil(o.Attempt) {
		return true
	}

	return false
}

// SetAttempt gets a reference to the given int32 and assigns it to the Attempt field.
func (o *AdapterStatusMetadata) SetAttempt(v int32) {
	o.Attempt = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *AdapterStatusMetadata) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatusMetadata) GetStartedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *AdapterStatusMetadata) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given time.Time and assigns it to the StartedAt field.
func (o *AdapterStatusMetadata) SetStartedAt(v time.Time) {
	o.StartedAt = &v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise.
func (o *AdapterStatusMetadata) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatusMetadata) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CompletedAt) {
		return nil, false
	}
	return o.CompletedAt, true
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *AdapterStatusMetadata) HasCompletedAt() bool {
	if o != nil && !IsNil(o.CompletedAt) {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given time.Time and assigns it to the CompletedAt field.
func (o *AdapterStatusMetadata) SetCompletedAt(v time.Time) {
	o.CompletedAt = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *AdapterStatusMetadata) GetDuration() string {
	if o == nil || IsNil(o.Duration) {
		var ret string
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatusMetadata) GetDurationOk() (*string, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *AdapterStatusMetadata) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given string and assigns it to the Duration field.
func (o *AdapterStatusMetadata) SetDuration(v string) {
	o.Duration = &v
}

func (o AdapterStatusMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdapterStatusMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobName) {
		toSerialize["job_name"] = o.JobName
	}
	if !IsNil(o.JobNamespace) {
		toSerialize["job_namespace"] = o.JobNamespace
	}
	if !IsNil(o.Attempt) {
		toSerialize["attempt"] = o.Attempt
	}
	if !IsNil(o.StartedAt) {
		toSerialize["started_at"] = o.StartedAt
	}
	if !IsNil(o.CompletedAt) {
		toSerialize["completed_at"] = o.CompletedAt
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	return toSerialize, nil
}

type NullableAdapterStatusMetadata struct {
	value *AdapterStatusMetadata
	isSet bool
}

func (v NullableAdapterStatusMetadata) Get() *AdapterStatusMetadata {
	return v.value
}

func (v *NullableAdapterStatusMetadata) Set(val *AdapterStatusMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableAdapterStatusMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableAdapterStatusMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdapterStatusMetadata(val *AdapterStatusMetadata) *NullableAdapterStatusMetadata {
	return &NullableAdapterStatusMetadata{value: val, isSet: true}
}

func (v NullableAdapterStatusMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdapterStatusMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
